import { sql } from 'drizzle-orm';
import { SubmissionStatus } from '@shared/enums/submission-status.enum.js';
import {
  check,
  index,
  integer,
  pgTable,
  smallint,
  text,
  unique,
  uuid,
} from 'drizzle-orm/pg-core';
import { timestamptz, sqlValue } from './columns.js';
import { submissionStatus } from './enums.js';
import { establishments } from './establishments.js';
import { tenantIsolation } from './policies.js';

/**
 * Registry of the numbers handed out: one row per declaration, never purged
 * (a deleted row would let its number be issued again). No data about the
 * injured person, ever. See docs/database.md for the numbering procedure.
 */
export const declarationSubmissions = pgTable(
  'declaration_submissions',
  {
    // Generated by the phone, so a retry is recognised (HL-06).
    idempotencyKey: uuid().primaryKey(),
    establishmentId: uuid()
      .notNull()
      .references(() => establishments.id),
    dossierYear: smallint().notNull(),
    dossierSeq: integer().notNull(),
    dossierNumber: text().generatedAlwaysAs(
      sql`dossier_year::text || '-' || lpad(dossier_seq::text, 7, '0')`,
    ),
    status: submissionStatus().notNull().default(SubmissionStatus.NUMBERED),
    receivedAt: timestamptz().notNull().defaultNow(),
    sentAt: timestamptz(),
    // Statistics (STAT-01). The hour only, never the date of the event.
    eventTypeCode: text().notNull(),
    locationCode: text().notNull(),
    eventHour: smallint().notNull(),
  },
  (t) => [
    tenantIsolation(),
    unique().on(t.establishmentId, t.dossierYear, t.dossierSeq),
    index('declaration_submissions_received_idx').on(
      t.establishmentId,
      t.receivedAt,
    ),
    index('declaration_submissions_month_idx').on(t.receivedAt),
    index('declaration_submissions_pending_idx')
      .on(t.receivedAt)
      .where(sql`status = ${sqlValue(SubmissionStatus.NUMBERED)}`),
    check(
      'declaration_submissions_year_check',
      sql`dossier_year BETWEEN 2020 AND 2999`,
    ),
    check(
      'declaration_submissions_seq_check',
      sql`dossier_seq BETWEEN 1 AND 9999999`,
    ),
    check(
      'declaration_submissions_hour_check',
      sql`event_hour BETWEEN 0 AND 23`,
    ),
    check(
      'declaration_submissions_sent_check',
      sql`(status = ${sqlValue(SubmissionStatus.SENT)}) = (sent_at IS NOT NULL)`,
    ),
  ],
);
