import type { components } from '@core/api/schema';

/** The DTOs of the API, generated by `pnpm api:types`. */
export type ApiSchemas = components['schemas'];

export type ApiErrorBody = ApiSchemas['ErrorBodyDto'];
export type ApiFieldError = ApiSchemas['FieldErrorDto'];

/** Every success body: `{ data }`, with `meta` on a paginated list. */
export interface ApiResponse<T> {
  data: T;
  meta?: Record<string, unknown>;
}
