/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/mobile/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_login_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/mobile/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_refresh_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_logout_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AuthController_me_v1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['SessionsController_list_v1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/sessions/{sessionId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['SessionsController_revokeOwn_v1'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/{userId}/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['SessionsController_revokeAllOfUser_v1'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    EstablishmentSummaryDto: {
      /** Format: uuid */
      id: string;
      /** @example École Saint-Denis */
      name: string;
    };
    AuthUserDto: {
      /** Format: uuid */
      id: string;
      /** @example lea.martin@ecole.fr */
      email: string;
      /** @example Léa */
      firstName: string;
      /** @example Martin */
      lastName: string;
      /** @enum {string} */
      role: 'intervenant' | 'responsable' | 'super_admin';
      establishment: components['schemas']['EstablishmentSummaryDto'] | null;
    };
    MobileLoginResponseDto: {
      accessToken: string;
      /** Format: date-time */
      accessTokenExpiresAt: string;
      refreshToken: string;
      /** Format: date-time */
      sessionExpiresAt: string;
      user: components['schemas']['AuthUserDto'];
    };
    MobileDeviceDto: {
      /** @description Stable identifier of the device */
      id: string;
      /** @example iPhone de Léa */
      name?: string;
      /** @enum {string} */
      platform: 'ios' | 'android';
      /** @example 1.0.0 */
      appVersion: string;
    };
    MobileLoginDto: {
      /** @example lea.martin@ecole.fr */
      email: string;
      password: string;
      device: components['schemas']['MobileDeviceDto'];
    };
    FieldErrorDto: {
      /** @example postalCode */
      field: string;
      /** @example matches */
      constraint: string;
      /** @example postalCode must be 5 digits */
      message: string;
    };
    ErrorBodyDto: {
      /** @example 404 */
      status: number;
      /**
       * @description Stable code clients branch on. The message may change.
       * @example STUDENT_NOT_FOUND
       */
      code: string;
      /**
       * @description For developers, in English.
       * @example Student not found
       */
      message: string;
      /**
       * @example {
       *       "studentId": "3f2a6c1e-0b8d-4d7e-9f5a-2c1b7e4d9a10"
       *     }
       */
      details?: {
        [key: string]: unknown;
      };
      fields?: components['schemas']['FieldErrorDto'][];
      /** @example b1c9e2f4-7a3d-4c1e-8b6a-0f2d9e5c3a71 */
      requestId?: string;
      /** Format: date-time */
      timestamp: string;
      /** @example /api/v1/students/3f2a6c1e */
      path: string;
    };
    ErrorResponseDto: {
      error: components['schemas']['ErrorBodyDto'];
    };
    TokenPairDto: {
      accessToken: string;
      /** Format: date-time */
      accessTokenExpiresAt: string;
      refreshToken: string;
      /** Format: date-time */
      sessionExpiresAt: string;
    };
    RefreshTokenDto: {
      refreshToken: string;
    };
    SubscriptionSummaryDto: {
      /** @enum {string} */
      status:
        'pending_payment' | 'active' | 'past_due' | 'suspended' | 'cancelled';
      /** Format: date-time */
      currentPeriodEnd: string | null;
    };
    MeResponseDto: {
      /** Format: uuid */
      id: string;
      /** @example lea.martin@ecole.fr */
      email: string;
      /** @example Léa */
      firstName: string;
      /** @example Martin */
      lastName: string;
      /** @enum {string} */
      role: 'intervenant' | 'responsable' | 'super_admin';
      establishment: components['schemas']['EstablishmentSummaryDto'] | null;
      /** @enum {string} */
      channel: 'mobile' | 'backoffice';
      subscription: components['schemas']['SubscriptionSummaryDto'] | null;
    };
    SessionResponseDto: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      channel: 'mobile' | 'backoffice';
      /** @example iPhone de Léa */
      deviceName: string | null;
      /** @example ios */
      platform: string | null;
      /** @example 1.0.0 */
      appVersion: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      lastUsedAt: string;
      /** @description The session of this request */
      current: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuthController_login_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MobileLoginDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['MobileLoginResponseDto'];
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  AuthController_refresh_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshTokenDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['TokenPairDto'];
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  AuthController_logout_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  AuthController_me_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['MeResponseDto'];
          };
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  SessionsController_list_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['SessionResponseDto'][];
          };
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  SessionsController_revokeOwn_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sessionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  SessionsController_revokeAllOfUser_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
}
