/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/mobile/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_login_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/mobile/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_refresh_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_logout_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AuthController_me_v1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/backoffice/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['BackofficeAuthController_login_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/backoffice/totp/enrolment': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['BackofficeAuthController_startEnrolment_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/backoffice/totp/enrolment/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['BackofficeAuthController_confirmEnrolment_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/backoffice/totp/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['BackofficeAuthController_verify_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/backoffice/totp/recovery': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['BackofficeAuthController_recover_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['SessionsController_list_v1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/sessions/{sessionId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['SessionsController_revokeOwn_v1'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/{userId}/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['SessionsController_revokeAllOfUser_v1'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/{userId}/totp/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['TotpAdminController_reset_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/invitations/lookup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['InvitationsController_lookup_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/invitations/acceptance': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['InvitationsController_accept_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/{userId}/invitation': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['UserInvitationController_resend_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sheet-recipients': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['SheetRecipientsController_find_v1'];
    put: operations['SheetRecipientsController_replace_v1'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/establishments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['EstablishmentsController_list_v1'];
    put?: never;
    post: operations['EstablishmentsController_create_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/establishments/cities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['EstablishmentsController_cities_v1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/establishments/{establishmentId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['EstablishmentsController_detail_v1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['EstablishmentsController_update_v1'];
    trace?: never;
  };
  '/api/v1/establishments/{establishmentId}/suspension': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['EstablishmentsController_suspend_v1'];
    delete: operations['EstablishmentsController_reactivate_v1'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/establishments/{establishmentId}/logo': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['EstablishmentsController_logo_v1'];
    put: operations['EstablishmentsController_setLogo_v1'];
    post?: never;
    delete: operations['EstablishmentsController_removeLogo_v1'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    EstablishmentSummaryDto: {
      /** Format: uuid */
      id: string;
      /** @example École Saint-Denis */
      name: string;
    };
    AuthUserDto: {
      /** Format: uuid */
      id: string;
      /** @example lea.martin@ecole.fr */
      email: string;
      /** @example Léa */
      firstName: string;
      /** @example Martin */
      lastName: string;
      /** @enum {string} */
      role: 'intervenant' | 'responsable' | 'super_admin';
      establishment: components['schemas']['EstablishmentSummaryDto'] | null;
    };
    MobileLoginResponseDto: {
      accessToken: string;
      /** Format: date-time */
      accessTokenExpiresAt: string;
      refreshToken: string;
      /** Format: date-time */
      sessionExpiresAt: string;
      user: components['schemas']['AuthUserDto'];
    };
    MobileDeviceDto: {
      /** @description Stable identifier of the device */
      id: string;
      /** @example iPhone de Léa */
      name?: string;
      /** @enum {string} */
      platform: 'ios' | 'android';
      /** @example 1.0.0 */
      appVersion: string;
    };
    MobileLoginDto: {
      /** @example lea.martin@ecole.fr */
      email: string;
      password: string;
      device: components['schemas']['MobileDeviceDto'];
    };
    FieldErrorDto: {
      /** @example postalCode */
      field: string;
      /** @example matches */
      constraint: string;
      /** @example postalCode must be 5 digits */
      message: string;
    };
    ErrorBodyDto: {
      /** @example 404 */
      status: number;
      /**
       * @description Stable code clients branch on. The message may change.
       * @example STUDENT_NOT_FOUND
       */
      code: string;
      /**
       * @description For developers, in English.
       * @example Student not found
       */
      message: string;
      /**
       * @example {
       *       "studentId": "3f2a6c1e-0b8d-4d7e-9f5a-2c1b7e4d9a10"
       *     }
       */
      details?: {
        [key: string]: unknown;
      };
      fields?: components['schemas']['FieldErrorDto'][];
      /** @example b1c9e2f4-7a3d-4c1e-8b6a-0f2d9e5c3a71 */
      requestId?: string;
      /** Format: date-time */
      timestamp: string;
      /** @example /api/v1/students/3f2a6c1e */
      path: string;
    };
    ErrorResponseDto: {
      error: components['schemas']['ErrorBodyDto'];
    };
    TokenPairDto: {
      accessToken: string;
      /** Format: date-time */
      accessTokenExpiresAt: string;
      refreshToken: string;
      /** Format: date-time */
      sessionExpiresAt: string;
    };
    RefreshTokenDto: {
      refreshToken: string;
    };
    SubscriptionSummaryDto: {
      /** @enum {string} */
      status:
        'pending_payment' | 'active' | 'past_due' | 'suspended' | 'cancelled';
      /** Format: date-time */
      currentPeriodEnd: string | null;
    };
    MeResponseDto: {
      /** Format: uuid */
      id: string;
      /** @example lea.martin@ecole.fr */
      email: string;
      /** @example Léa */
      firstName: string;
      /** @example Martin */
      lastName: string;
      /** @enum {string} */
      role: 'intervenant' | 'responsable' | 'super_admin';
      establishment: components['schemas']['EstablishmentSummaryDto'] | null;
      /** @enum {string} */
      channel: 'mobile' | 'backoffice';
      subscription: components['schemas']['SubscriptionSummaryDto'] | null;
    };
    ChallengeResponseDto: {
      /** @enum {string} */
      step: 'totp_verification' | 'totp_enrolment';
      challengeToken: string;
      /** Format: date-time */
      challengeExpiresAt: string;
    };
    BackofficeLoginDto: {
      /** @example responsable@demo.senami.fr */
      email: string;
      password: string;
    };
    TotpEnrolmentResponseDto: {
      /** @description To draw the QR code from */
      otpauthUrl: string;
      /** @description Base32 secret, for manual entry */
      secret: string;
    };
    ChallengeDto: {
      challengeToken: string;
    };
    EnrolmentConfirmedResponseDto: {
      user: components['schemas']['AuthUserDto'];
      /** @description Shown once, never again */
      recoveryCodes: string[];
    };
    TotpCodeDto: {
      challengeToken: string;
      /** @example 123456 */
      code: string;
    };
    BackofficeSessionResponseDto: {
      user: components['schemas']['AuthUserDto'];
    };
    RecoveryResponseDto: {
      user: components['schemas']['AuthUserDto'];
      remainingRecoveryCodes: number;
    };
    RecoveryCodeDto: {
      challengeToken: string;
      /** @example K7Q2M-9XWPA */
      recoveryCode: string;
    };
    SessionResponseDto: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      channel: 'mobile' | 'backoffice';
      /** @example iPhone de Léa */
      deviceName: string | null;
      /** @example ios */
      platform: string | null;
      /** @example 1.0.0 */
      appVersion: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      lastUsedAt: string;
      /** @description The session of this request */
      current: boolean;
    };
    InvitationResponseDto: {
      firstName: string;
      email: string;
      /** @enum {string} */
      role: 'intervenant' | 'responsable' | 'super_admin';
      establishmentName: string | null;
      establishmentCity: string | null;
      /** Format: date-time */
      expiresAt: string;
    };
    InvitationTokenDto: {
      /** @description From the # of the invitation link */
      token: string;
    };
    AcceptInvitationDto: {
      /** @description From the # of the invitation link */
      token: string;
      password: string;
    };
    ResentInvitationResponseDto: {
      /** Format: date-time */
      expiresAt: string;
    };
    SheetRecipientsResponseDto: {
      to: string[];
      cc: string[];
      bcc: string[];
      /**
       * Format: date-time
       * @description null: no recipient saved yet
       */
      updatedAt: string | null;
    };
    UpdateSheetRecipientsDto: {
      /**
       * @example [
       *       "direction@ecole.fr"
       *     ]
       */
      to: string[];
      /**
       * @example [
       *       "infirmerie@ecole.fr"
       *     ]
       */
      cc: string[];
      /** @example [] */
      bcc: string[];
    };
    EstablishmentResponsableDto: {
      /** Format: uuid */
      userId: string;
      firstName: string;
      lastName: string;
      email: string;
      /** @enum {string} */
      status: 'invited' | 'active' | 'deactivated';
      isSecondFactorEnrolled: boolean;
    };
    EstablishmentSubscriptionDto: {
      /** @enum {string} */
      status:
        'pending_payment' | 'active' | 'past_due' | 'suspended' | 'cancelled';
      planName: string;
      /** Format: date-time */
      currentPeriodEnd: string | null;
    };
    EstablishmentSummaryResponseDto: {
      /** Format: uuid */
      id: string;
      name: string;
      /** @enum {string} */
      type: 'maternelle' | 'primaire' | 'college' | 'lycee' | 'groupe_scolaire';
      city: string;
      /** @enum {string} */
      status: 'active' | 'suspended' | 'terminated';
      isDemo: boolean;
      /** Format: date-time */
      createdAt: string;
      responsable: components['schemas']['EstablishmentResponsableDto'] | null;
      subscription:
        components['schemas']['EstablishmentSubscriptionDto'] | null;
      /** @description A counter, never a sheet */
      declarationsThisMonth: number;
    };
    PaginationMeta: {
      /** @example 1 */
      page: number;
      /** @example 20 */
      limit: number;
      /** @example 312 */
      total: number;
      /** @example 16 */
      totalPages: number;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
    };
    String: Record<string, never>;
    UserCountDto: {
      /** @enum {string} */
      role: 'intervenant' | 'responsable' | 'super_admin';
      /** @enum {string} */
      status: 'invited' | 'active' | 'deactivated';
      count: number;
    };
    EstablishmentDetailResponseDto: {
      /** Format: uuid */
      id: string;
      name: string;
      /** @enum {string} */
      type: 'maternelle' | 'primaire' | 'college' | 'lycee' | 'groupe_scolaire';
      city: string;
      /** @enum {string} */
      status: 'active' | 'suspended' | 'terminated';
      isDemo: boolean;
      /** Format: date-time */
      createdAt: string;
      responsable: components['schemas']['EstablishmentResponsableDto'] | null;
      subscription:
        components['schemas']['EstablishmentSubscriptionDto'] | null;
      /** @description A counter, never a sheet */
      declarationsThisMonth: number;
      addressLine: string;
      postalCode: string;
      phone: string | null;
      email: string | null;
      approxStudentCount: number | null;
      hasLogo: boolean;
      /** Format: date-time */
      suspendedAt: string | null;
      suspensionReason: string | null;
      users: components['schemas']['UserCountDto'][];
    };
    InvitationOutcomeDto: {
      /** @description false: the email failed, resend it */
      sent: boolean;
      /** Format: date-time */
      expiresAt: string;
    };
    CreatedEstablishmentResponseDto: {
      establishment: components['schemas']['EstablishmentDetailResponseDto'];
      invitation: components['schemas']['InvitationOutcomeDto'];
    };
    EstablishmentFieldsDto: {
      /** @example École Sainte-Marie */
      name: string;
      /** @enum {string} */
      type: 'maternelle' | 'primaire' | 'college' | 'lycee' | 'groupe_scolaire';
      /** @example 12 rue des Écoles */
      addressLine: string;
      /** @example 59000 */
      postalCode: string;
      /** @example Lille */
      city: string;
      /** @example 03 20 00 00 00 */
      phone?: string | null;
      /** @example contact@ecole.fr */
      email?: string | null;
      /** @example 250 */
      approxStudentCount?: number | null;
    };
    ResponsableDto: {
      /** @example Claire */
      firstName: string;
      /** @example Houngbo */
      lastName: string;
      /** @example direction@ecole.fr */
      email: string;
    };
    CreateEstablishmentDto: {
      establishment: components['schemas']['EstablishmentFieldsDto'];
      responsable: components['schemas']['ResponsableDto'];
    };
    UpdateEstablishmentDto: {
      /** @example École Sainte-Marie */
      name?: string;
      /** @enum {string} */
      type?:
        'maternelle' | 'primaire' | 'college' | 'lycee' | 'groupe_scolaire';
      /** @example 12 rue des Écoles */
      addressLine?: string;
      /** @example 59000 */
      postalCode?: string;
      /** @example Lille */
      city?: string;
      /** @example 03 20 00 00 00 */
      phone?: string | null;
      /** @example contact@ecole.fr */
      email?: string | null;
      /** @example 250 */
      approxStudentCount?: number | null;
    };
    SuspendEstablishmentDto: {
      /** @example Abonnement impayé depuis septembre */
      reason: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuthController_login_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MobileLoginDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['MobileLoginResponseDto'];
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  AuthController_refresh_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshTokenDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['TokenPairDto'];
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  AuthController_logout_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  AuthController_me_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['MeResponseDto'];
          };
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  BackofficeAuthController_login_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BackofficeLoginDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['ChallengeResponseDto'];
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  BackofficeAuthController_startEnrolment_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChallengeDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['TotpEnrolmentResponseDto'];
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  BackofficeAuthController_confirmEnrolment_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TotpCodeDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['EnrolmentConfirmedResponseDto'];
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  BackofficeAuthController_verify_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TotpCodeDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['BackofficeSessionResponseDto'];
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  BackofficeAuthController_recover_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RecoveryCodeDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['RecoveryResponseDto'];
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  SessionsController_list_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['SessionResponseDto'][];
          };
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  SessionsController_revokeOwn_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sessionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  SessionsController_revokeAllOfUser_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  TotpAdminController_reset_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  InvitationsController_lookup_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['InvitationTokenDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['InvitationResponseDto'];
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  InvitationsController_accept_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AcceptInvitationDto'];
      };
    };
    responses: {
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  UserInvitationController_resend_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['ResentInvitationResponseDto'];
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  SheetRecipientsController_find_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['SheetRecipientsResponseDto'];
          };
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  SheetRecipientsController_replace_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateSheetRecipientsDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['SheetRecipientsResponseDto'];
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  EstablishmentsController_list_v1: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        /** @description Name or responsable email */
        search?: string;
        city?: string;
        status?: 'active' | 'suspended' | 'terminated';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['EstablishmentSummaryResponseDto'][];
            meta: components['schemas']['PaginationMeta'];
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  EstablishmentsController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateEstablishmentDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['CreatedEstablishmentResponseDto'];
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  EstablishmentsController_cities_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['String'][];
          };
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  EstablishmentsController_detail_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        establishmentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['EstablishmentDetailResponseDto'];
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  EstablishmentsController_update_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        establishmentId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateEstablishmentDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['EstablishmentDetailResponseDto'];
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  EstablishmentsController_suspend_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        establishmentId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SuspendEstablishmentDto'];
      };
    };
    responses: {
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  EstablishmentsController_reactivate_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        establishmentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  EstablishmentsController_logo_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        establishmentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  EstablishmentsController_setLogo_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        establishmentId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          logo?: string;
        };
      };
    };
    responses: {
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
  EstablishmentsController_removeLogo_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        establishmentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponseDto'];
        };
      };
    };
  };
}
