// @ts-check
import eslint from '@eslint/js';
import nextVitals from 'eslint-config-next/core-web-vitals';
import prettier from 'eslint-config-prettier';
import { defineConfig, globalIgnores } from 'eslint/config';
import globals from 'globals';
import react from 'react/package.json' with { type: 'json' };
import tseslint from 'typescript-eslint';

// Typed linting: rules such as no-floating-promises need the type checker,
// which `projectService` wires from tsconfig.json.
export default defineConfig(
  globalIgnores([
    '.next/**',
    'out/**',
    'coverage/**',
    'playwright-report/**',
    'test-results/**',
    'next-env.d.ts',
    // Generated by `pnpm api:types`.
    'src/core/api/schema.d.ts',
  ]),
  eslint.configs.recommended,
  ...nextVitals,
  ...tseslint.configs.recommendedTypeChecked,
  prettier,
  {
    // eslint-plugin-react cannot detect the version under ESLint 10.
    settings: { react: { version: react.version } },
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
      parserOptions: {
        // The *.mjs configs are outside tsconfig.json: use the default project.
        projectService: { allowDefaultProject: ['*.mjs'] },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // Outside the current folder, import through an alias (@shared/...).
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              regex: '^\\.\\./',
              message:
                'Use an alias (@app, @config, @core, @features, @shared) instead of ../',
            },
          ],
        },
      ],
      // Domain values come from their enum (UserRole, SessionChannel), never
      // from a string written by hand.
      'no-restricted-syntax': [
        'error',
        {
          selector:
            'Literal[value=/^(intervenant|responsable|super_admin|mobile|backoffice)$/]',
          message:
            'Use the enum (UserRole, SessionChannel) instead of a hard-coded value.',
        },
      ],
      // Casing rules of docs/conventions.md#naming. The most specific
      // selector wins, whatever the order.
      '@typescript-eslint/naming-convention': [
        'error',
        { selector: 'default', format: ['camelCase'] },
        {
          selector: 'parameter',
          format: ['camelCase'],
          leadingUnderscore: 'allow',
        },
        // UPPER_CASE for constants, PascalCase for components.
        {
          selector: 'variable',
          format: ['camelCase', 'UPPER_CASE', 'PascalCase'],
          leadingUnderscore: 'allow',
        },
        { selector: 'variable', modifiers: ['destructured'], format: null },
        { selector: 'function', format: ['camelCase', 'PascalCase'] },
        { selector: 'typeLike', format: ['PascalCase'] },
        {
          selector: 'interface',
          format: ['PascalCase'],
          custom: { regex: '^I[A-Z]', match: false },
        },
        { selector: 'enumMember', format: ['UPPER_CASE'] },
        { selector: 'classProperty', format: ['camelCase', 'UPPER_CASE'] },
        // Shapes owned by others: HTTP headers, payloads, computed keys.
        {
          selector: ['objectLiteralProperty', 'typeProperty'],
          format: null,
        },
        { selector: 'import', format: null },
      ],
    },
  },
  {
    // Where the values are defined.
    files: ['src/shared/enums/*.enum.ts'],
    rules: { 'no-restricted-syntax': 'off' },
  },
);
